import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://cdn.pixabay.com/photo/2016/01/03/00/43/upload-1118929_640.png" />
        <title>V-Uploader</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
